### ISSUE TITLE
:global often conflicts with selector-class-pattern

### ISSUE THREAD

**Issue by Nfinished** [pascalduez/stylelint-config-css-modules#12]
It's not uncommon that selectors targeted with :global don't conform to the established class pattern, is disabling the rule for these instances within the scope of this project?

**Comment by pascalduez** [comment]
Hi @Nfinished,

could you be a bit more explicit, provide a few examples etc.? 
Not sure exactly what your referring to. 
Usage of the `:global` selector is indeed in the scope of this config.

**Comment by pascalduez** [comment]
The error you get is because of the `selector-class-pattern` rule, enforced by `stylelint-config-standard`.    
So it's your responsibility to override this rule in your project, not `stylelint-config-css-modules`.     
`stylelint-config-css-modules` is just a couple of overrides to be able to use CSS modules specific syntax.
